# Generated by Django 6.0.6 on 2026-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام نوع گزارش')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('color_hex', models.CharField(default='#00ff88', max_length=7, verbose_name='رنگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'نوع گزارش',
                'verbose_name_plural': 'انواع گزارش',
                'ordering': ['name'],
            },
        ),
    ]
