# Generated by Django 6.0.6 on 2026-07-01 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام صنعت')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد صنعت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'صنعت',
                'verbose_name_plural': 'صنایع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام شرکت')),
                ('symbol', models.CharField(max_length=50, unique=True, verbose_name='نماد')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='نام انگلیسی')),
                ('company_type', models.CharField(blank=True, choices=[('بورس', 'بورس'), ('فرابورس', 'فرابورس'), ('پایه', 'پایه فرابورس')], default='بورس', max_length=20, verbose_name='نوع بازار')),
                ('isin', models.CharField(blank=True, max_length=20, verbose_name='کد ISIN')),
                ('tsetmc_code', models.CharField(blank=True, max_length=20, verbose_name='کد تسنیم')),
                ('codal_url', models.URLField(blank=True, verbose_name='آدرس کدال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.sector', verbose_name='صنعت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
                'ordering': ['symbol'],
            },
        ),
    ]
